import { Step } from "../../step";
import { KeyedStore } from "../../stores/keyed-store";
import { UnkeyedStore } from "../../stores/unkeyed-store";

/**
 * Indicates that a {@link Step} is to be executed when the build process starts.
 */
export type OneTimeTrigger = {
  /**
   * Specifies that this is a {@link OneTimeTrigger}.
   */
  readonly type: `oneTime`;

  /**
   * Invoked on first run.
   * @returns The {@link Step} which is to be executed in response.
   */
  up(): Step;

  /**
   * The stores to which the steps generated by this trigger write to (whether setting or deleting) on execution.
   */
  readonly writesToStores: ReadonlyArray<
    UnkeyedStore<unknown> | KeyedStore<unknown>
  >;
};
